### PR TITLE
feat: added shiden crowdloan page

### PR DESCRIPTION
**Pull request by impelcrypto**
* Added Shiden crowdloan page
* path: http://localhost:8080/#/shiden

Demo (Deployed):
https://crowdloan-app-impelcrypto.vercel.app/#/shiden
@sirius651 @hoonsubin  btw, we can deploy the Vue3 app to [vercel](https://vercel.com/solutions/vue) for staging easily (it's for free).

to-dos:
* implement contribution logic
* update meta data
* update sentences @fiexer @hoonsubin please refer to [this](https://github.com/AstarNetwork/crowdloan-app/blob/df511c1c833eaf1cf21b71d7425bba1df994f180/src/data/shiden/AppData.ts) file and feel free to update it.
  * https://user-images.githubusercontent.com/92044428/164508616-b993c821-5861-44b7-8b8c-03eb6eb39c02.png

Desktop:
localhost_8080_ (1)

image

Mobile:

### CODE REVIEW

**Comment by bobo-k2** [comment]
I am getting some linter errors locally. I see that linter passed on CI. Can you please check?
Beside that everything looks good.
image

**Comment by Kahonnohak** [comment]
Thank you @impelcrypto 

It's hard to find out the exact styling since I can't read the code, and it is already great but few things I wanted to check with you.

- Hero

The H1 title looks small and would like it a little bit go up. Have you used a trick to make the content stay centre?
For the font size, looking at the screenshot you could + 5px, please. 

スクリーンショット 2022-04-22 9 04 01


- Join

We need review for the texts but in styling, I have two requests.

1. The colour of zero - #555
2. The font weight of the rewards - same to other numbers
スクリーンショット 2022-04-22 9 20 47


- Paddings

The paddings in each section looks bit tight, maybe around 80px now but could you make it 120, please?
スクリーンショット 2022-04-22 9 20 04

---
I never thought you could join the CL from mobile but probably you can from Nova and Math5? awesome.

**Comment by impelcrypto** [comment]
@bobo-k2 
> I am getting some linter errors locally. I see that linter passed on CI. Can you please check?

Yes, I am aware of this. Those linter errors are from existing code maintained by @sirius651 . I think @sirius651  can take a look at this issue.

**Comment by impelcrypto** [comment]
@Kahonnohak 
>  Have you used a trick to make the content stay center?

Yes.

**Comment by impelcrypto** [comment]
@Kahonnohak 

Fixed.
I've deployed manually.
https://crowdloan-app-impelcrypto.vercel.app/#/shiden

**Comment by impelcrypto** [comment]
@Kahonnohak 
I've adjusted the position of hero UI.

image

**Comment by impelcrypto** [comment]
@Kahonnohak 
I adjusted hero UI styling

image

**Comment by impelcrypto** [comment]
@Kahonnohak 

> I never thought you could join the CL from mobile but probably you can from Nova and Math5? awesome.

Yes, I believe so.

**Review by sirius651 — APPROVED** [review]
Awesome work

**Review by hoonsubin — APPROVED** [review]
LGTM

**Comment by Kahonnohak** [comment]
Hi @impelcrypto 
The form area is finalised, please take a look.
スクリーンショット 2022-04-25 16 45 42


Also please add the links for Astar Network and Shiden Network LPs on the header and remove the link for the forum. We might not need FAQ and still need someone to review and get the text information.

スクリーンショット 2022-04-25 16 46 27

Figma
https://www.figma.com/file/iKuvjDsoNqmJ5kjeO5xHMF/Portal-V2?node-id=2283%3A25254

Let me know if you have any questions. thanks

**Pull request closed without merging**
